site_name: Ánalisis de tráfico de red
site_url: https://Nick-Saim-MJ.github.io/Analisis_de_trafico_de_red/
repo_url: https://github.com/Nick-Saim-MJ/Analisis_de_trafico_de_red
repo_name: Nick-Saim-MJ/Analisis_de_trafico_de_red
docs_dir: docs

nav:
  - Inicio: index.md
  - Proyecto Ánalisis de tráfico de red:
      - Brief del Proyecto: proyecto-sello/brief.md

  - 1. Producto U1:
      - "Informe - Unidad 1": productos/Informe_Unidad_1.md
      - "Métodologia CRISPDM": productos/Aplicacion_de_CRISPDM_al_Proyecto.md
      - "Producto U1 (S5 - u1-producto.md)": productos/u1-producto.md

      - 1.1 Contribución por Integrante:
          - "Nick": contribuidores/u1_producto_nick.md
          - "Henyelrey": contribuidores/u1_producto_henyelrey.md
          - "Jhan": contribuidores/u1_producto_jhan.md
          - "David": contribuidores/u1_producto_david.md
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
