name: lambda26-ec-orden-prod

services:
  postgres-ec-orden:
    image: postgres:16-alpine
    container_name: lambda26-postgres-ec-orden
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "49020:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - lambda26_postgres_ec_orden_data:/var/lib/postgresql/data
    networks:
      - lambda26-ec-orden-net

  ec-orden-ms:
    build: .
    container_name: lambda26-ec-orden
    restart: unless-stopped
    depends_on:
      postgres-ec-orden:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EC_KAFKA_BOOTSTRAP_SERVERS: ${EC_KAFKA_BOOTSTRAP_SERVERS}
      DB_HOST: lambda26-postgres-ec-orden
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./logs:/app/logs
    ports:
      - "49021:8080"
    networks:
      - lambda26-ec-orden-net
      - lambda26-kafka-net

volumes:
  lambda26_postgres_ec_orden_data:

networks:
  lambda26-ec-orden-net:
    name: lambda26-ec-orden-net
  lambda26-kafka-net:
    external: true
    name: lambda26-kafka-net
