name: trafico-red-pyspark

services:
  pyspark:
    container_name: trafico-red-pyspark
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4488:8888"
      - "4045:4042"
    volumes:
      - ./data:/opt/data
      - ./producto:/opt/producto
      - ./artifacts:/opt/artifacts
    environment:
      - JUPYTER_TOKEN=sintoken
