name: lambda26-pyspark

services:
  pyspark:
    container_name: lambda26-pyspark
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4488:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/opt/notebooks
      - ./data:/opt/data
      - ./artifacts:/opt/artifacts
    environment:
      - JUPYTER_TOKEN=sintoken
