name: lambda26-kafka

services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: lambda26-kafka
    restart: unless-stopped
    ports:
      - "49092:49092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:49092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      lambda26-kafka-net:
        aliases:
          - kafka

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.10.0
    container_name: lambda26-kafka-exporter
    restart: unless-stopped
    command:
      - --kafka.server=kafka:9092
    depends_on:
      - kafka
    ports:
      - "49308:9308"
    networks:
      lambda26-kafka-net:
        aliases:
          - kafka-exporter

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.5.0
    container_name: lambda26-kafka-ui
    restart: unless-stopped
    ports:
      - "48085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: lambda26
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - lambda26-kafka-net

networks:
  lambda26-kafka-net:
    name: lambda26-kafka-net
